export default [
  {
    transport: [
      {
        type: 'bicycle',
        name: 'Max',
        slug: 'a',
        amount: 500,
        distance: 50,
        start: 'New hall, Unilag',
        stop: 'Moremi Hall',
      },
      {
        type: 'bus-new',
        name: 'BRT',
        amount: 0,
        slug: 'b',
        distance: 45,
        start: 'Moremi Hall',
        stop: 'DLI',
      },
      {
        type: 'bicycle',
        name: 'Max',
        amount: 500,
        slug: 'c',
        distance: 70,
        start: 'DLI',
        stop: 'Kofo Hall',
      },
    ],
    duration: 0,
    total: 1000,
    bookLink: '',
  },
  {
    transport: [
      {
        type: 'car',
        name: 'Zeno Car',
        amount: 500,
        slug: 'd',
        distance: 70,
        start: 'Herbert Macaulay',
        stop: 'Jibowu',
      },
      {
        type: 'bus-new',
        name: 'Zeno bus',
        amount: 350,
        slug: 'e',
        distance: 40,
        start: 'Jibowu',
        stop: 'Ojuelegba',
      },
      {
        type: 'car',
        name: 'Zeno Car',
        amount: 500,
        slug: 'f',
        distance: 30,
        start: 'Ojuelegba',
        stop: 'Yaba',
      },
    ],
    duration: '1:40mins',
    total: 1350,
    bookLink: '',
  },
  {
    transport: [
      {
        type: 'car',
        name: 'Bolt',
        amount: 700,
        slug: 'g',
        distance: 60,
        start: 'Lekki phase II',
        stop: 'Mega Chicken',
      },
      {
        type: 'bus-new',
        name: 'Zeno Bus',
        amount: 350,
        slug: 'h',
        distance: 10,
        start: 'Mega Chicken',
        stop: 'Ikota first gate',
      },
      {
        type: 'car',
        name: 'Bolt',
        amount: 700,
        slug: 'i',
        distance: 20,
        start: 'Ikota first gate',
        stop: 'Swisstrade doors',
      },
    ],
    duration: '1:40mins',
    total: 1750,
    bookLink: '',
  },
  {
    transport: [
      {
        type: 'car',
        name: 'Uber',
        amount: 1000,
        slug: 'j',
        distance: 70,
        start: 'Lekki phase II',
        stop: 'Mega Chicken',
      },
      {
        type: 'bus',
        name: 'Zeno Bus',
        amount: 350,
        slug: 'k',
        distance: 40,
        start: 'Mega Chicken',
        stop: 'Ikota first gate',
      },
      {
        type: 'car',
        name: 'Uber',
        amount: 1000,
        slug: 'l',
        distance: 80,
        start: 'Ikota first gate',
        stop: 'Swisstrade doors',
      },
    ],
    duration: '1:40mins',
    total: 2350,
    bookLink: '',
  },
  {
    transport: [
      {
        type: 'car',
        name: 'Max',
        amount: 1000,
        slug: 'm',
        distance: 70,
        start: 'New hall, Unilag',
        stop: 'Moremi Hall',
      },
      {
        type: 'bus',
        name: 'Rail',
        amount: 350,
        slug: 'n',
        distance: 70,
        start: 'Moremi Hall',
        stop: 'DLI',
      },
      {
        type: 'car',
        name: 'Max',
        amount: 1500,
        slug: 'o',
        distance: 70,
        start: 'DLI',
        stop: 'Kofo Hall',
      },
    ],
    duration: '1:40mins',
    total: 2850,
    bookLink: '',
  },
];
